# Generated by stackage2nix 0.4.0 from "/nix/store/y9cbijn0b3kwh5rb6vm30ya5qbsrpxwm-stackage-lts/lts-9.0.yaml"
{ nixpkgs ? import <nixpkgs> {} }:

with nixpkgs; let
  haskellLib = callPackage (nixpkgs.path + /pkgs/development/haskell-modules/lib.nix) {};
in callPackage (nixpkgs.path + /pkgs/development/haskell-modules) {
  ghc = pkgs.haskell.compiler.ghc802;
  compilerConfig = import  ./configuration-packages.nix { inherit pkgs haskellLib; };
  initialPackages = import ./packages.nix;
  configurationCommon = if builtins.pathExists ./configuration-common.nix then import ./configuration-common.nix else args: self: super: {};
  inherit haskellLib;
}
