# Generated by stackage2nix 0.7.2 from "/nix/store/6nhazjk3wgalhgrzicf1my2y4sk5311z-source/lts-13.3.yaml"
{ pkgs, haskellLib }:

with haskellLib; self: super: {

  # core packages
  "array" = null;
  "base" = null;
  "binary" = null;
  "bytestring" = null;
  "containers" = null;
  "deepseq" = null;
  "directory" = null;
  "filepath" = null;
  "ghc-boot" = null;
  "ghc-boot-th" = null;
  "ghc-heap" = null;
  "ghc-prim" = null;
  "ghci" = null;
  "hpc" = null;
  "integer-gmp" = null;
  "pretty" = null;
  "process" = null;
  "rts" = null;
  "template-haskell" = null;
  "terminfo" = null;
  "time" = null;
  "transformers" = null;
  "unix" = null;
  # break cycle: HUnit call-stack nanospec hspec hspec-core clock tasty async hashable test-framework-hunit tasty-quickcheck tasty-hunit hspec-expectations quickcheck-io hspec-discover hspec-meta silently temporary exceptions
  "exceptions" = dontCheck super.exceptions;
  "temporary" = dontCheck super.temporary;
  "silently" = dontCheck super.silently;
  "hspec-discover" = dontCheck super.hspec-discover;
  "hashable" = dontCheck super.hashable;
  "async" = dontCheck super.async;
  "clock" = dontCheck super.clock;
  "nanospec" = dontCheck super.nanospec;

}
