# Generated by stackage2nix 0.4.0 from "./stack.yaml"
{ nixpkgs ? import <nixpkgs> {} }:

with nixpkgs;
let
  inherit (stdenv.lib) extends;
  stackagePackages = self: import ./packages.nix { inherit pkgs stdenv; inherit (self) callPackage; };
  stackageConfig = callPackage ./configuration-packages.nix {};
  stackPackages =
    { pkgs, stdenv, callPackage }:

    self: {
      "stackage2nix" = callPackage
        ({ mkDerivation, aeson, base, bytestring, Cabal, cabal2nix
         , containers, deepseq, distribution-nixpkgs, exceptions, filepath
         , gitlib, gitlib-libgit2, hopenssl, hspec, inflections
         , language-nix, lens, network-uri, optparse-applicative, pretty
         , QuickCheck, shakespeare, stackage-curator, text
         , unordered-containers, yaml
         }:
         mkDerivation {
           pname = "stackage2nix";
           version = "0.4.0";
           src = fetchgit {
             url = "https://github.com/typeable/stackage2nix.git";
             rev = "e24850b131b9c271e9a2cf238e41fb116b523d35";
             sha256 = "1xak8bdjpcbp6mkwk8879ax39nf9229j5jcv1hl9v652rgiax1qa";
           };
           isLibrary = true;
           isExecutable = true;
           libraryHaskellDepends = [
             aeson base bytestring Cabal cabal2nix containers deepseq
             distribution-nixpkgs exceptions filepath gitlib gitlib-libgit2
             hopenssl inflections language-nix lens network-uri
             optparse-applicative pretty QuickCheck stackage-curator text
             unordered-containers yaml
           ];
           executableHaskellDepends = [ base ];
           testHaskellDepends = [
             base bytestring Cabal hspec pretty shakespeare text yaml
           ];
           doHaddock = false;
           doCheck = false;
           homepage = "https://github.com/4e6/stackage2nix#readme";
           description = "Convert Stack files into Nix build instructions";
           license = stdenv.lib.licenses.bsd3;
         }) {};
    };

  pkgOverrides = self: stackPackages {
    inherit pkgs stdenv;
    inherit (self) callPackage;
  };

in callPackage (nixpkgs.path + "/pkgs/development/haskell-modules") {
  ghc = pkgs.haskell.compiler.ghc822;
  compilerConfig = self: extends pkgOverrides (extends stackageConfig (stackagePackages self));
  haskellLib = callPackage (nixpkgs.path + "/pkgs/development/haskell-modules/lib.nix") {};
  initialPackages = args: self: {};
  configurationCommon = args: self: super: {};
}
