# Generated by stackage2nix 0.4.0 from "/home/dbushev/projects/fpco/lts-haskell/lts-10.0.yaml"
{ nixpkgs ? import <nixpkgs> {} }:

with nixpkgs; let
  haskellLib = callPackage (nixpkgs.path + /pkgs/development/haskell-modules/lib.nix) {};
in callPackage (nixpkgs.path + /pkgs/development/haskell-modules) {
  ghc = pkgs.haskell.compiler.ghc822;
  compilerConfig = import  ./configuration-packages.nix { inherit pkgs haskellLib; };
  initialPackages = import ./packages.nix;
  configurationCommon = if builtins.pathExists ./configuration-common.nix then import ./configuration-common.nix else args: self: super: {};
  inherit haskellLib;
}
