# Generated by stackage2nix 0.4.0 from "/home/dbushev/projects/fpco/lts-haskell/lts-6.30.yaml"
{ nixpkgs ? import <nixpkgs> {} }:

with nixpkgs;
let
  inherit (stdenv.lib) extends;
  stackagePackages = self: import ./packages.nix { inherit pkgs stdenv; inherit (self) callPackage; };
  stackageConfig = callPackage ./configuration-packages.nix {};
in callPackage (nixpkgs.path + /pkgs/development/haskell-modules) {
  ghc = pkgs.haskell.compiler.ghc7103;
  compilerConfig = self: extends stackageConfig (stackagePackages self);
  haskellLib = callPackage (nixpkgs.path + /pkgs/development/haskell-modules/lib.nix) {};
  initialPackages = args: self: {};
  configurationCommon = args: self: super: {};
}
