# Generated by stackage2nix 0.5.0 from "/nix/store/7qx86j1c631k9189wq1b8na3psv9g51w-stackage-lts/lts-10.2.yaml"
{ callPackage, pkgs, overrides ? (self: super: {})
, packageSetConfig ? (sefl: super: {})
}:

let
  haskellLib = pkgs.haskell.lib;
in callPackage (<nixpkgs/pkgs/development/haskell-modules>) {
  ghc = pkgs.haskell.compiler.ghc822;
  compilerConfig = import  ./configuration-packages.nix { inherit pkgs haskellLib; };
  initialPackages = import ./packages.nix;
  configurationCommon = if builtins.pathExists ./configuration-common.nix then import ./configuration-common.nix else args: self: super: {};
  inherit haskellLib overrides packageSetConfig;
}
